export const initialState = data => ({
  email: data?.email || '',
  phone: data?.phoneNumber || '',
  name: data?.displayName || '',
  password: '',
  confirm_password: '',
  profile_pic: data?.photoURL || '',
  role: '',
  uid: data?.uid || '',
});

export const formFields = [
  {
    name: 'name',
    type: 'name',
    keyboardType: 'default',
    label: 'Name',
    placeholder: 'Enter your full name',
    required: true,
    disabled: false,
  },
  {
    name: 'email',
    type: 'emailAddress',
    keyboardType: 'email-address',
    label: 'Email',
    placeholder: 'Enter your email',
    required: true,
    disabled: true,
  },
  {
    name: 'phone',
    type: 'telephoneNumber',
    keyboardType: 'phone-pad',
    label: 'Phone',
    placeholder: 'Enter your phone number',
    required: true,
    disabled: false,
    maxLength: 10,
    minLength: 10,
  },
  {
    name: 'password',
    type: 'password',
    keyboardType: 'default',
    label: 'Password',
    placeholder: 'Enter your password',
    required: true,
    maxLength: 20,
    minLength: 6,
  },
  // {
  //   name: 'confirm_password',
  //   type: 'password',
  //   keyboardType: 'default',
  //   label: 'Confirm Password',
  //   placeholder: 'Confirm your password',
  //   required: true,
  // },
  {
    name: 'role',
    type: 'radio',
    keyboardType: 'radio',
    label: 'You want to use the application as a:',
    placeholder: 'Select your role',
    required: true,
  },
];
